env:
  DOTNET_VERSION: '7.0.x'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release
                  
      - name: Get version
        id: get_version
        uses: greenygh0st/net-proj-release-version@v1
        with:
          PROJ_FILE: src/PuppetMaster.Client.UI/PuppetMaster.Client.UI.csproj

      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: src/PuppetMaster.Client.UI/Releases/*.*
          name: "Version ${{ steps.get_version.outputs.RELEASE_VERSION }}"
          tag: "${{ steps.get_version.outputs.RELEASE_VERSION }}"
